# SonarCloud: https://sonarcloud.io
sonar.organization=abhishekshankar
sonar.projectKey=abhishekshankar_fertilityshare
sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=syllabus
sonar.tests=syllabus/tests
